### ISSUE TITLE
Layout issue of the readme

### ISSUE THREAD

**Issue by PricelessCode** [PricelessCode/Ultimate-Guide-To-Algorithm#1]
As the size of algorithms readme gets larger, the design of the readme / either new structure of the project is needed

**Comment by pragyakhanna11** [comment]
The readme could be organised in a tabular form with links to separate pages for algorithms , linkedlist etc, other columns could contain link to explanation, resources and so on.

If you would like that please assign the issue to me and I'll work on it.

**Comment by PricelessCode** [comment]
Thank you for the suggestion, @pragyakhanna11  :) 
I think your idea sounds good!
Would you maybe like to work on the overall layout it as you mentioned?

Meanwhile I will work on adding another algorithm.
Feel free to tag me on issues or any other btw :)

**Comment by PricelessCode** [comment]
@pragyakhanna11 
Regarding this issue, I am thinking of using AstroJS for visualizing the markdown files separated by the topics.
The design will probably looking like this.

I am working on this design. Will be applied by end of this week.

![image](https://github.com/PricelessCode/Ultimate-Guide-To-Algorithm/assets/30044760/505fc08f-0bda-4d88-8d1d-39cefda9b3e6)

What do you guys think?

CC. @Nananaw

**Comment by Nananaw** [comment]
looks good!
